"use client";

import React, { useEffect, useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Loading } from "@/components/Loading";
import { cn } from "@/lib/utils";
import * as api from "@/lib/api";
import type { ThreatBriefingSummary } from "@/types";
import {
  ScrollText,
  Loader2,
  Sparkles,
  Calendar,
  ChevronDown,
  ChevronUp,
  AlertTriangle,
  Shield,
  Swords,
  Skull,
  Download,
  FileText,
  Code2,
} from "lucide-react";

/* ─── Build styled HTML content for a briefing ─────────── */
function buildBriefingHTML(b: ThreatBriefingSummary): string {
  const dateRange = `${b.period_start ? new Date(b.period_start).toLocaleDateString() : "—"} — ${b.period_end ? new Date(b.period_end).toLocaleDateString() : "—"}`;
  const campaigns = (b.key_campaigns || []).map((c: any) => `<li><strong>${c.campaign_name || c.name || c}</strong>${c.actor_name ? ` — ${c.actor_name}` : ""}${c.description ? `<br/><small>${c.description}</small>` : ""}</li>`).join("");
  const vulns = (b.key_vulnerabilities || []).map((v: any) => `<li>${typeof v === "string" ? v : v.cve || v.cve_id || v.name || JSON.stringify(v)}</li>`).join("");
  const actors = (b.key_actors || []).map((a: any) => `<li>${typeof a === "string" ? a : a.actor || a.name || JSON.stringify(a)}</li>`).join("");
  const recs = (b.recommendations || []).map((r: string, i: number) => `<li>${i + 1}. ${r}</li>`).join("");
  const stats = b.stats ? `<p><strong>Articles:</strong> ${b.stats.articles_processed ?? b.stats.total_articles ?? 0} | <strong>CVEs:</strong> ${b.stats.new_cves ?? b.stats.total_cves ?? 0} | <strong>Campaigns:</strong> ${b.stats.new_campaigns ?? b.stats.total_campaigns ?? 0}</p>` : "";
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>${b.title}</title><style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#1a1a1a;line-height:1.6}h1{font-size:24px;border-bottom:2px solid #6d28d9;padding-bottom:8px}h2{font-size:16px;color:#6d28d9;margin-top:24px;border-bottom:1px solid #e5e7eb;padding-bottom:4px}.meta{color:#6b7280;font-size:13px;margin-bottom:16px}.stats{background:#f3f4f6;padding:12px 16px;border-radius:8px;margin:12px 0;font-size:13px}ul{padding-left:20px}li{margin-bottom:6px}@media print{body{margin:20px}}</style></head><body><h1>${b.title}</h1><div class="meta">${b.period} · ${dateRange} · Generated by IntelWatch</div><div class="stats">${stats}</div><h2>Executive Summary</h2><p>${(b.executive_summary || "").replace(/\n/g, "<br/>")}</p>${campaigns ? `<h2>Key Campaigns</h2><ul>${campaigns}</ul>` : ""}${vulns ? `<h2>Key Vulnerabilities</h2><ul>${vulns}</ul>` : ""}${actors ? `<h2>Key Threat Actors</h2><ul>${actors}</ul>` : ""}${recs ? `<h2>Recommendations</h2><ul>${recs}</ul>` : ""}<hr/><p style="font-size:11px;color:#9ca3af;">Generated by IntelWatch Threat Intelligence Platform</p></body></html>`;
}

function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function downloadHTML(b: ThreatBriefingSummary) {
  const safeName = (b.title || "briefing").replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 60);
  downloadBlob(buildBriefingHTML(b), `${safeName}.html`, "text/html");
}

function downloadPDF(b: ThreatBriefingSummary) {
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(buildBriefingHTML(b));
    printWindow.document.close();
    setTimeout(() => { printWindow.print(); }, 500);
  }
}

export default function BriefingsPage() {
  const [briefings, setBriefings] = useState<ThreatBriefingSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const data = await api.getBriefings(20);
      setBriefings(data);
    } catch (e) {
      console.error("Failed to load briefings", e);
    }
    setLoading(false);
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const resp = await api.generateBriefing(7) as Record<string, any>;
      const briefing = resp.briefing || resp;
      const b: ThreatBriefingSummary = {
        id: resp.id || "new",
        period: briefing.period || "weekly",
        period_start: briefing.period_start,
        period_end: briefing.period_end,
        title: briefing.title || "Weekly Threat Brief",
        executive_summary: briefing.executive_summary || "",
        key_campaigns: briefing.key_campaigns,
        key_vulnerabilities: briefing.key_vulnerabilities,
        key_actors: briefing.key_actors,
        recommendations: briefing.recommendations || [],
        stats: briefing.stats || resp.raw_data?.stats,
      };
      setBriefings((prev) => [b, ...prev]);
      setExpandedId(b.id);
    } catch (e) {
      console.error("Failed to generate briefing", e);
    }
    setGenerating(false);
  };

  if (loading && briefings.length === 0) return <Loading text="Loading threat briefings..." />;

  return (
    <div className="p-4 md:p-6 space-y-5 max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold flex items-center gap-2">
            <ScrollText className="h-5 w-5 text-primary" />
            Threat Briefings
          </h1>
          <p className="text-sm text-muted-foreground">
            AI-generated executive threat intelligence summaries
          </p>
        </div>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="flex items-center gap-1.5 px-4 py-2 rounded-md bg-primary text-primary-foreground text-xs font-medium hover:bg-primary/90 transition-colors disabled:opacity-50"
        >
          {generating ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Sparkles className="h-3.5 w-3.5" />}
          Generate Weekly Briefing
        </button>
      </div>

      {/* Briefings List */}
      {briefings.length === 0 ? (
        <Card>
          <CardContent className="py-16 text-center text-muted-foreground">
            <ScrollText className="h-12 w-12 mx-auto mb-3 opacity-30" />
            <p className="text-lg">No briefings yet</p>
            <p className="text-sm mt-1">Click &ldquo;Generate Weekly Briefing&rdquo; to create your first AI-powered threat summary.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {briefings.map((b) => {
            const isExpanded = expandedId === b.id;
            return (
              <Card key={b.id} className="border-l-2 border-primary/30">
                <div
                  className="px-5 py-4 cursor-pointer hover:bg-muted/20 transition-colors"
                  onClick={() => setExpandedId(isExpanded ? null : b.id)}
                >
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <h3 className="text-sm font-semibold">{b.title}</h3>
                        <Badge variant="outline" className="text-[9px]">{b.period}</Badge>
                        {/* Download buttons */}
                        <div className="ml-auto flex items-center gap-1" onClick={(e) => e.stopPropagation()}>
                          <button onClick={() => downloadPDF(b)} title="Download PDF" className="p-1 rounded hover:bg-muted transition-colors"><FileText className="h-3.5 w-3.5 text-red-400" /></button>
                          <button onClick={() => downloadHTML(b)} title="Download HTML" className="p-1 rounded hover:bg-muted transition-colors"><Code2 className="h-3.5 w-3.5 text-blue-400" /></button>
                        </div>
                      </div>
                      <p className="text-xs text-muted-foreground line-clamp-2">
                        {b.executive_summary}
                      </p>
                      <div className="flex items-center gap-3 mt-2 text-[10px] text-muted-foreground">
                        <span className="flex items-center gap-1">
                          <Calendar className="h-3 w-3" />
                          {b.period_start ? new Date(b.period_start).toLocaleDateString() : "—"} — {b.period_end ? new Date(b.period_end).toLocaleDateString() : "—"}
                        </span>
                        {b.stats && (
                          <>
                            <span>{b.stats.articles_processed ?? b.stats.total_articles} articles</span>
                            <span>{b.stats.new_cves ?? b.stats.total_cves} CVEs</span>
                            <span>{b.stats.new_campaigns ?? b.stats.total_campaigns} campaigns</span>
                          </>
                        )}
                      </div>
                    </div>
                    {isExpanded ? (
                      <ChevronUp className="h-4 w-4 text-muted-foreground shrink-0 mt-1" />
                    ) : (
                      <ChevronDown className="h-4 w-4 text-muted-foreground shrink-0 mt-1" />
                    )}
                  </div>
                </div>

                {isExpanded && (
                  <div className="px-5 pb-5 pt-1 border-t border-border/20 space-y-4">
                    {/* Executive Summary */}
                    <div>
                      <h4 className="text-xs font-semibold text-muted-foreground mb-1">Executive Summary</h4>
                      <p className="text-sm leading-relaxed whitespace-pre-wrap">{b.executive_summary}</p>
                    </div>

                    {/* Key Campaigns */}
                    {b.key_campaigns && b.key_campaigns.length > 0 && (
                      <div>
                        <h4 className="text-xs font-semibold text-muted-foreground mb-2 flex items-center gap-1">
                          <Swords className="h-3 w-3" /> Key Campaigns
                        </h4>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                          {b.key_campaigns.map((c: any, i: number) => (
                            <div key={i} className="p-2.5 rounded-md border bg-violet-500/[0.03]">
                              <span className="text-xs font-semibold text-violet-400">{c.campaign_name || c.name || c}</span>
                              {c.actor_name && <span className="ml-2 text-[10px] text-red-400"><Skull className="inline h-2.5 w-2.5 mr-0.5" />{c.actor_name}</span>}
                              {c.severity && <Badge variant="outline" className="ml-1 text-[8px]">{c.severity}</Badge>}
                              {c.targeted_sectors && c.targeted_sectors.length > 0 && (
                                <div className="flex flex-wrap gap-1 mt-1">{c.targeted_sectors.slice(0, 3).map((s: string, j: number) => <Badge key={j} variant="secondary" className="text-[8px]">{s}</Badge>)}</div>
                              )}
                              {c.description && <p className="text-[10px] text-muted-foreground mt-0.5">{c.description}</p>}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Key Vulnerabilities */}
                    {b.key_vulnerabilities && b.key_vulnerabilities.length > 0 && (
                      <div>
                        <h4 className="text-xs font-semibold text-muted-foreground mb-2 flex items-center gap-1">
                          <AlertTriangle className="h-3 w-3" /> Key Vulnerabilities
                        </h4>
                        <div className="flex flex-wrap gap-1.5">
                          {b.key_vulnerabilities.map((v: any, i: number) => {
                            const label = typeof v === "string" ? v : v.cve_id || v.cve || v.name;
                            const exploited = typeof v === "object" && (v.is_exploited || v.is_kev);
                            return (
                              <Badge key={i} variant="outline" className={cn("text-[10px]", exploited ? "text-red-400 border-red-400/40" : "text-primary")}>
                                {label}{exploited && <span className="ml-1 text-[8px] text-red-300">KEV</span>}
                              </Badge>
                            );
                          })}
                        </div>
                      </div>
                    )}

                    {/* Key Actors */}
                    {b.key_actors && b.key_actors.length > 0 && (
                      <div>
                        <h4 className="text-xs font-semibold text-muted-foreground mb-2 flex items-center gap-1">
                          <Skull className="h-3 w-3" /> Key Threat Actors
                        </h4>
                        <div className="flex flex-wrap gap-1.5">
                          {b.key_actors.map((a: any, i: number) => {
                            const name = typeof a === "string" ? a : a.name || a.actor;
                            const mentions = typeof a === "object" ? a.mentions || a.count : null;
                            const category = typeof a === "object" ? a.category || a.type : null;
                            return (
                              <Badge key={i} variant="outline" className="text-[10px] text-red-400">
                                {name}{mentions ? <span className="ml-1 text-muted-foreground">({mentions})</span> : null}{category ? <span className="ml-1 text-[8px] text-muted-foreground">{category}</span> : null}
                              </Badge>
                            );
                          })}
                        </div>
                      </div>
                    )}

                    {/* Recommendations */}
                    {b.recommendations && b.recommendations.length > 0 && (
                      <div>
                        <h4 className="text-xs font-semibold text-muted-foreground mb-2 flex items-center gap-1">
                          <Shield className="h-3 w-3" /> Recommendations
                        </h4>
                        <ul className="space-y-1.5">
                          {b.recommendations.map((r: string, i: number) => (
                            <li key={i} className="flex items-start gap-2 text-xs">
                              <span className="text-primary font-bold shrink-0 mt-0.5">{i + 1}.</span>
                              <span className="text-muted-foreground">{r}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Download action bar */}
                    <div className="flex items-center gap-2 pt-3 border-t border-border/30">
                      <button onClick={() => downloadPDF(b)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-red-500/10 text-red-400 text-[11px] font-medium hover:bg-red-500/20 transition-colors">
                        <Download className="h-3 w-3" /> Download PDF
                      </button>
                      <button onClick={() => downloadHTML(b)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-blue-500/10 text-blue-400 text-[11px] font-medium hover:bg-blue-500/20 transition-colors">
                        <Download className="h-3 w-3" /> Download HTML
                      </button>
                    </div>
                  </div>
                )}
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
